  name: Typescript
  on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
  jobs:

    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 23.7.0
            cache: npm

        - name: Install Hardhat
          run: npm install --save-dev hardhat@2.22.17

        - name: Install Dependencies
          run: npm install

        - name: Compile Contracts
          run: npx hardhat compile --force

        - name: Run Hardhat Test
          run: npx hardhat test --typecheck

        - name: Install Solhint
          run: npm install -g solhint

        - name: Run Lint
          run: solhint 'contracts/**/*.sol'
